import React, { useEffect } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/index.module.scss'

const Home: NextPage = () => {
  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async (): Promise<void> => {
    const response = await fetch("https://opentdb.com/api.php?amount=10&category=9&difficulty=easy&type=multiple");
    const data = await response.json();
    window.localStorage.setItem('results', JSON.stringify(data.results))
  };

  return (
    <div>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          퀴즈에 환영합니다!
        </h1>
        <Link href="/quiz">
          <a className={styles.quizButton}>퀴즈 풀기</a>
        </Link>
      </main>
    </div>
  )
}

export default Home
