import React, { useEffect, useState } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Quiz: NextPage = () => {
  const [data, setData] = useState([] as any[]);
  const [questionCount, setQuestionCount] = useState(0)
  const [answerCount, setAnswerCount] = useState(0)

  useEffect(() => {
    const results = JSON.parse(window.localStorage.getItem('results') || '{}')
    setData(results)
  }, []);

  const handleClick = (value: boolean): void => {
    setQuestionCount(questionCount => questionCount + 1)
    if (value) {
      setAnswerCount(answerCount => answerCount + 1)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">the quiz</a>
        </h1>
        {data.slice(questionCount, questionCount + 1).map((d, index) => (
          <div key={index}>
            <p dangerouslySetInnerHTML={{ __html: d.question }} />
            {d.incorrect_answers.map((d: string) => (
              <p key={d} dangerouslySetInnerHTML={{ __html: d }} onClick={() => handleClick(false)} />
            ))}
            <p dangerouslySetInnerHTML={{ __html: d.correct_answer }} onClick={() => handleClick(true)} />
          </div>
        ))}

        {questionCount !== data.length && (
          <p>questionCount: {questionCount + 1} out of {data.length}</p>
        )}

        {questionCount === data.length && (
          <p>answerCount: {answerCount}</p>
        )}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Quiz
